# Generated by Django 5.2.6 on 2025-09-06 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balancete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balancetes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('category', models.CharField(choices=[('Faturamento', 'Faturamento'), ('Despesa', 'Despesa')], default='Despesa', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('boleto_img', models.ImageField(blank=True, null=True, upload_to='boletos/')),
                ('balancete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boletos', to='personal_finance.balancete')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
