# Generated by Django 5.2.6 on 2025-09-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_finance', '0002_balancete_boleto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancete',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
